### ISSUE TITLE
Logs are not printed prettily in interactive shell

### ISSUE THREAD

**Issue by ZeroRin** [Dragon2fly/logger_tt#17]
after calling `setup_logging`, printing logs in interactive shell may result in `>>> ` in front of some of the lines.
![image](https://user-images.githubusercontent.com/14952735/209539314-8e122b98-3344-4cf8-ac28-4dd13767e444.png)

and the last line can sometimes be lost if I input new texts

**Comment by Dragon2fly** [comment]
Hi @ZeroRin 

There are two kinds of output here. One is from the interactive shell ('>>>' and your typing) and one is from the logger handling thread.

Due to the thread processing nature, the output of the logger is not continuous. 
While the logger is printing or waiting for data on the queue, the os may switch back to the interactive shell thread and it prints out `>>>`.

For the loss of the last log line, I can only assume the race condition between the interactive shell thread and the logger thread.

So is it a problem for you or what are you trying to archive?

**Comment by Dragon2fly** [comment]
Since `LogConfig` replaces all handlers with QueueHandler, I think it is easier to stop that from happening with a flag.
i.e. pass a parameter to `setup_logging` and edit the method [`_set_mode`](https://github.com/Dragon2fly/logger_tt/blob/4fa1975f12125d1c65e59e65cb5398a2eb0547e6/logger_tt/core.py#L86).
